    spring.application.name=simpleWebApp
    server.port=8080

#    spring.datasource.url=jdbc:h2:mem:testdb
#    spring.datasource.driverClassName=org.h2.Driver
#    spring.datasource.username=sa
#    spring.datasource.password=
#    spring.datasource.show-sql=true
#    spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#
#    # Enable H2 console
#    spring.h2.console.enabled=true
#    spring.h2.console.path=/h2-console


#spring.data.mongodb.uri=mongodb://localhost:27017/simpleWebApp


spring.datasource.url=jdbc:postgresql://localhost:5432/simpleWebApp
spring.datasource.username=postgres
spring.datasource.password=gullu
spring.jpa.hibernate.ddl-auto=update


spring.security.user.name=chitransh
spring.security.user.password=gullu



